image:
    file: gitpod.dockerfile
tasks:
    - init: . ${GITPOD_REPO_ROOT}/gitpod.tasks.sh
ports:
    - port: 80
    
    ## python, django:
    - port: 8000

    # node, livereload:
    - port: 8080
    - port: 3001
    - port: 35729 